// Code generated by go-swagger; DO NOT EDIT.

// Package apiserver vault-query
//
//	This is a simple api to query vault for policies and entities
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /
//	Version: 1.0.0
//	Contact: <subbaksh@cisco.com>
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package apiserver
