// Code generated by go-swagger; DO NOT EDIT.

package group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetGroupByNameParams creates a new GetGroupByNameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetGroupByNameParams() *GetGroupByNameParams {
	return &GetGroupByNameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetGroupByNameParamsWithTimeout creates a new GetGroupByNameParams object
// with the ability to set a timeout on a request.
func NewGetGroupByNameParamsWithTimeout(timeout time.Duration) *GetGroupByNameParams {
	return &GetGroupByNameParams{
		timeout: timeout,
	}
}

// NewGetGroupByNameParamsWithContext creates a new GetGroupByNameParams object
// with the ability to set a context for a request.
func NewGetGroupByNameParamsWithContext(ctx context.Context) *GetGroupByNameParams {
	return &GetGroupByNameParams{
		Context: ctx,
	}
}

// NewGetGroupByNameParamsWithHTTPClient creates a new GetGroupByNameParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetGroupByNameParamsWithHTTPClient(client *http.Client) *GetGroupByNameParams {
	return &GetGroupByNameParams{
		HTTPClient: client,
	}
}

/*
GetGroupByNameParams contains all the parameters to send to the API endpoint

	for the get group by name operation.

	Typically these are written to a http.Request.
*/
type GetGroupByNameParams struct {

	/* GroupName.

	   name of the group
	*/
	GroupName string

	/* Namespace.

	   namespace of the group
	*/
	Namespace *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get group by name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetGroupByNameParams) WithDefaults() *GetGroupByNameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get group by name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetGroupByNameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get group by name params
func (o *GetGroupByNameParams) WithTimeout(timeout time.Duration) *GetGroupByNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get group by name params
func (o *GetGroupByNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get group by name params
func (o *GetGroupByNameParams) WithContext(ctx context.Context) *GetGroupByNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get group by name params
func (o *GetGroupByNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get group by name params
func (o *GetGroupByNameParams) WithHTTPClient(client *http.Client) *GetGroupByNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get group by name params
func (o *GetGroupByNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithGroupName adds the groupName to the get group by name params
func (o *GetGroupByNameParams) WithGroupName(groupName string) *GetGroupByNameParams {
	o.SetGroupName(groupName)
	return o
}

// SetGroupName adds the groupName to the get group by name params
func (o *GetGroupByNameParams) SetGroupName(groupName string) {
	o.GroupName = groupName
}

// WithNamespace adds the namespace to the get group by name params
func (o *GetGroupByNameParams) WithNamespace(namespace *string) *GetGroupByNameParams {
	o.SetNamespace(namespace)
	return o
}

// SetNamespace adds the namespace to the get group by name params
func (o *GetGroupByNameParams) SetNamespace(namespace *string) {
	o.Namespace = namespace
}

// WriteToRequest writes these params to a swagger request
func (o *GetGroupByNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param groupName
	if err := r.SetPathParam("groupName", o.GroupName); err != nil {
		return err
	}

	if o.Namespace != nil {

		// query param namespace
		var qrNamespace string

		if o.Namespace != nil {
			qrNamespace = *o.Namespace
		}
		qNamespace := qrNamespace
		if qNamespace != "" {

			if err := r.SetQueryParam("namespace", qNamespace); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
