// Code generated by go-swagger; DO NOT EDIT.

package policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"vaultquery/models"
)

// NewQueryPolicyParams creates a new QueryPolicyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewQueryPolicyParams() *QueryPolicyParams {
	return &QueryPolicyParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewQueryPolicyParamsWithTimeout creates a new QueryPolicyParams object
// with the ability to set a timeout on a request.
func NewQueryPolicyParamsWithTimeout(timeout time.Duration) *QueryPolicyParams {
	return &QueryPolicyParams{
		timeout: timeout,
	}
}

// NewQueryPolicyParamsWithContext creates a new QueryPolicyParams object
// with the ability to set a context for a request.
func NewQueryPolicyParamsWithContext(ctx context.Context) *QueryPolicyParams {
	return &QueryPolicyParams{
		Context: ctx,
	}
}

// NewQueryPolicyParamsWithHTTPClient creates a new QueryPolicyParams object
// with the ability to set a custom HTTPClient for a request.
func NewQueryPolicyParamsWithHTTPClient(client *http.Client) *QueryPolicyParams {
	return &QueryPolicyParams{
		HTTPClient: client,
	}
}

/*
QueryPolicyParams contains all the parameters to send to the API endpoint

	for the query policy operation.

	Typically these are written to a http.Request.
*/
type QueryPolicyParams struct {

	// Body.
	Body *models.Request

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the query policy params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *QueryPolicyParams) WithDefaults() *QueryPolicyParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the query policy params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *QueryPolicyParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the query policy params
func (o *QueryPolicyParams) WithTimeout(timeout time.Duration) *QueryPolicyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the query policy params
func (o *QueryPolicyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the query policy params
func (o *QueryPolicyParams) WithContext(ctx context.Context) *QueryPolicyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the query policy params
func (o *QueryPolicyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the query policy params
func (o *QueryPolicyParams) WithHTTPClient(client *http.Client) *QueryPolicyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the query policy params
func (o *QueryPolicyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the query policy params
func (o *QueryPolicyParams) WithBody(body *models.Request) *QueryPolicyParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the query policy params
func (o *QueryPolicyParams) SetBody(body *models.Request) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *QueryPolicyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
