// Code generated by go-swagger; DO NOT EDIT.

package policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSearchPolicyParams creates a new SearchPolicyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSearchPolicyParams() *SearchPolicyParams {
	return &SearchPolicyParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSearchPolicyParamsWithTimeout creates a new SearchPolicyParams object
// with the ability to set a timeout on a request.
func NewSearchPolicyParamsWithTimeout(timeout time.Duration) *SearchPolicyParams {
	return &SearchPolicyParams{
		timeout: timeout,
	}
}

// NewSearchPolicyParamsWithContext creates a new SearchPolicyParams object
// with the ability to set a context for a request.
func NewSearchPolicyParamsWithContext(ctx context.Context) *SearchPolicyParams {
	return &SearchPolicyParams{
		Context: ctx,
	}
}

// NewSearchPolicyParamsWithHTTPClient creates a new SearchPolicyParams object
// with the ability to set a custom HTTPClient for a request.
func NewSearchPolicyParamsWithHTTPClient(client *http.Client) *SearchPolicyParams {
	return &SearchPolicyParams{
		HTTPClient: client,
	}
}

/*
SearchPolicyParams contains all the parameters to send to the API endpoint

	for the search policy operation.

	Typically these are written to a http.Request.
*/
type SearchPolicyParams struct {

	// Body.
	Body SearchPolicyBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the search policy params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SearchPolicyParams) WithDefaults() *SearchPolicyParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the search policy params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SearchPolicyParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the search policy params
func (o *SearchPolicyParams) WithTimeout(timeout time.Duration) *SearchPolicyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the search policy params
func (o *SearchPolicyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the search policy params
func (o *SearchPolicyParams) WithContext(ctx context.Context) *SearchPolicyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the search policy params
func (o *SearchPolicyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the search policy params
func (o *SearchPolicyParams) WithHTTPClient(client *http.Client) *SearchPolicyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the search policy params
func (o *SearchPolicyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the search policy params
func (o *SearchPolicyParams) WithBody(body SearchPolicyBody) *SearchPolicyParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the search policy params
func (o *SearchPolicyParams) SetBody(body SearchPolicyBody) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *SearchPolicyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
