// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/runtime/security"
	"github.com/go-openapi/spec"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"vaultquery/pkg/apiserver/operations/auth"
	"vaultquery/pkg/apiserver/operations/group"
	"vaultquery/pkg/apiserver/operations/policy"
)

// NewVaultQueryAPI creates a new VaultQuery instance
func NewVaultQueryAPI(spec *loads.Document) *VaultQueryAPI {
	return &VaultQueryAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		PreServerShutdown:   func() {},
		ServerShutdown:      func() {},
		spec:                spec,
		useSwaggerUI:        false,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,

		JSONConsumer: runtime.JSONConsumer(),

		JSONProducer: runtime.JSONProducer(),

		PolicyGetPolicyByNameHandler: policy.GetPolicyByNameHandlerFunc(func(params policy.GetPolicyByNameParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation policy.GetPolicyByName has not yet been implemented")
		}),
		PolicyPolicyTreeHandler: policy.PolicyTreeHandlerFunc(func(params policy.PolicyTreeParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation policy.PolicyTree has not yet been implemented")
		}),
		PolicyQueryPolicyAllowedHandler: policy.QueryPolicyAllowedHandlerFunc(func(params policy.QueryPolicyAllowedParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation policy.QueryPolicyAllowed has not yet been implemented")
		}),
		AuthSearchAuthWithPolicyHandler: auth.SearchAuthWithPolicyHandlerFunc(func(params auth.SearchAuthWithPolicyParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation auth.SearchAuthWithPolicy has not yet been implemented")
		}),
		GroupSearchGroupWithPolicyHandler: group.SearchGroupWithPolicyHandlerFunc(func(params group.SearchGroupWithPolicyParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation group.SearchGroupWithPolicy has not yet been implemented")
		}),
		PolicySearchPolicyHandler: policy.SearchPolicyHandlerFunc(func(params policy.SearchPolicyParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation policy.SearchPolicy has not yet been implemented")
		}),

		// Applies when the "X-VAULT-TOKEN" header is set
		TokenAccessorAuthAuth: func(token string) (interface{}, error) {
			return nil, errors.NotImplemented("api key auth (TokenAccessorAuth) X-VAULT-TOKEN from header param [X-VAULT-TOKEN] has not yet been implemented")
		},
		// default authorizer is authorized meaning no requests are blocked
		APIAuthorizer: security.Authorized(),
	}
}

/*VaultQueryAPI This is a simple api to query vault for policies and entities */
type VaultQueryAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler
	useSwaggerUI    bool

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator

	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator

	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for the following mime types:
	//   - application/json
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for the following mime types:
	//   - application/json
	JSONProducer runtime.Producer

	// TokenAccessorAuthAuth registers a function that takes a token and returns a principal
	// it performs authentication based on an api key X-VAULT-TOKEN provided in the header
	TokenAccessorAuthAuth func(string) (interface{}, error)

	// APIAuthorizer provides access control (ACL/RBAC/ABAC) by providing access to the request and authenticated principal
	APIAuthorizer runtime.Authorizer

	// PolicyGetPolicyByNameHandler sets the operation handler for the get policy by name operation
	PolicyGetPolicyByNameHandler policy.GetPolicyByNameHandler
	// PolicyPolicyTreeHandler sets the operation handler for the policy tree operation
	PolicyPolicyTreeHandler policy.PolicyTreeHandler
	// PolicyQueryPolicyAllowedHandler sets the operation handler for the query policy allowed operation
	PolicyQueryPolicyAllowedHandler policy.QueryPolicyAllowedHandler
	// AuthSearchAuthWithPolicyHandler sets the operation handler for the search auth with policy operation
	AuthSearchAuthWithPolicyHandler auth.SearchAuthWithPolicyHandler
	// GroupSearchGroupWithPolicyHandler sets the operation handler for the search group with policy operation
	GroupSearchGroupWithPolicyHandler group.SearchGroupWithPolicyHandler
	// PolicySearchPolicyHandler sets the operation handler for the search policy operation
	PolicySearchPolicyHandler policy.SearchPolicyHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// PreServerShutdown is called before the HTTP(S) server is shutdown
	// This allows for custom functions to get executed before the HTTP(S) server stops accepting traffic
	PreServerShutdown func()

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// UseRedoc for documentation at /docs
func (o *VaultQueryAPI) UseRedoc() {
	o.useSwaggerUI = false
}

// UseSwaggerUI for documentation at /docs
func (o *VaultQueryAPI) UseSwaggerUI() {
	o.useSwaggerUI = true
}

// SetDefaultProduces sets the default produces media type
func (o *VaultQueryAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *VaultQueryAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *VaultQueryAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *VaultQueryAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *VaultQueryAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *VaultQueryAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *VaultQueryAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the VaultQueryAPI
func (o *VaultQueryAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.TokenAccessorAuthAuth == nil {
		unregistered = append(unregistered, "XVAULTTOKENAuth")
	}

	if o.PolicyGetPolicyByNameHandler == nil {
		unregistered = append(unregistered, "policy.GetPolicyByNameHandler")
	}
	if o.PolicyPolicyTreeHandler == nil {
		unregistered = append(unregistered, "policy.PolicyTreeHandler")
	}
	if o.PolicyQueryPolicyAllowedHandler == nil {
		unregistered = append(unregistered, "policy.QueryPolicyAllowedHandler")
	}
	if o.AuthSearchAuthWithPolicyHandler == nil {
		unregistered = append(unregistered, "auth.SearchAuthWithPolicyHandler")
	}
	if o.GroupSearchGroupWithPolicyHandler == nil {
		unregistered = append(unregistered, "group.SearchGroupWithPolicyHandler")
	}
	if o.PolicySearchPolicyHandler == nil {
		unregistered = append(unregistered, "policy.SearchPolicyHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *VaultQueryAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *VaultQueryAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {
	result := make(map[string]runtime.Authenticator)
	for name := range schemes {
		switch name {
		case "TokenAccessorAuth":
			scheme := schemes[name]
			result[name] = o.APIKeyAuthenticator(scheme.Name, scheme.In, o.TokenAccessorAuthAuth)

		}
	}
	return result
}

// Authorizer returns the registered authorizer
func (o *VaultQueryAPI) Authorizer() runtime.Authorizer {
	return o.APIAuthorizer
}

// ConsumersFor gets the consumers for the specified media types.
// MIME type parameters are ignored here.
func (o *VaultQueryAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {
	result := make(map[string]runtime.Consumer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONConsumer
		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result
}

// ProducersFor gets the producers for the specified media types.
// MIME type parameters are ignored here.
func (o *VaultQueryAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {
	result := make(map[string]runtime.Producer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONProducer
		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result
}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *VaultQueryAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the vault query API
func (o *VaultQueryAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *VaultQueryAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened
	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/policy/fetch/{policyName}"] = policy.NewGetPolicyByName(o.context, o.PolicyGetPolicyByNameHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/policy/tree"] = policy.NewPolicyTree(o.context, o.PolicyPolicyTreeHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/policy/query/allowed"] = policy.NewQueryPolicyAllowed(o.context, o.PolicyQueryPolicyAllowedHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/auth/search/policy"] = auth.NewSearchAuthWithPolicy(o.context, o.AuthSearchAuthWithPolicyHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/group/search/policy"] = group.NewSearchGroupWithPolicy(o.context, o.GroupSearchGroupWithPolicyHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/policy/search"] = policy.NewSearchPolicy(o.context, o.PolicySearchPolicyHandler)
}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *VaultQueryAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	if o.useSwaggerUI {
		return o.context.APIHandlerSwaggerUI(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *VaultQueryAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *VaultQueryAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *VaultQueryAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}

// AddMiddlewareFor adds a http middleware to existing handler
func (o *VaultQueryAPI) AddMiddlewareFor(method, path string, builder middleware.Builder) {
	um := strings.ToUpper(method)
	if path == "/" {
		path = ""
	}
	o.Init()
	if h, ok := o.handlers[um][path]; ok {
		o.handlers[method][path] = builder(h)
	}
}
